### ISSUE TITLE
minHeight Property to prevent the panel from disappearing 

### ISSUE THREAD

**Issue by salehahmedZ** [AdamJonsson/snapping_sheet#1]
Thank you for this amazing package.
I'm wondering is it possible to add a minHeight property to prevent the panel from disappear.
Now when I slide the panel really fast down below it just disappear.

Thanks

**Comment by AdamJonsson** [comment]
Thanks for raising an issue ☺️ It seems like a bug that the sheet is disappearing. Do you think you can send the part of your code that is using the snappingSheet widget?

**Comment by salehahmedZ** [comment]
```dart
class UseSnapSheetExample extends StatefulWidget {
  @override
  _UseSnapSheetExampleState createState() => _UseSnapSheetExampleState();
}

class _UseSnapSheetExampleState extends State<UseSnapSheetExample> with SingleTickerProviderStateMixin {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Use example'),
      ),
      body: SnappingSheet(
        snapPositions: const [
          SnapPosition(positionPixel: 0.0, snappingCurve: Curves.elasticOut, snappingDuration: Duration(milliseconds: 750)),
          SnapPosition(positionFactor: 0.4),
          SnapPosition(positionFactor: 0.8),
        ],
        child: GoogleMap(
          initialCameraPosition: CameraPosition(
            zoom: 3,
            target: LatLng(44, 44),
          ),
        ),
        grabbingHeight: MediaQuery.of(context).padding.bottom + 50,
        grabbing: GrabSection(),
        sheetBelow: buildContent(),
      ),
    );
  }

  Widget buildContent() {
    return Container(
      color: Colors.white,
      child: ListView.builder(
        padding: EdgeInsets.all(20.0),
        itemCount: 50,
        itemBuilder: (context, index) {
          return Container(
            decoration: BoxDecoration(border: Border(bottom: BorderSide(color: Colors.grey[300], width: 1.0))),
            child: ListTile(
              leading: Icon(Icons.info),
              title: Text('List item $index'),
            ),
          );
        },
      ),
    );
  }
}

```

**Comment by salehahmedZ** [comment]
I think the issue here is related to GoogleMap package.

**Comment by salehahmedZ** [comment]
BTW this only effect iOS devices not an Android

**Comment by AdamJonsson** [comment]
I have made som research and it seems that when a gesture detector is overflowing the screen while using UiKitView, flutter assert an error that state.down is not true. See this [Issue](https://github.com/flutter/flutter/issues/24207).

Like you said, adding minHeight and maxHeight can hopefully fix the problem. I should be able to add this option before the end of this week. Am also going to create or comment on an issue on Flutter to see if there are something they can do. 

Tank again

**Comment by AdamJonsson** [comment]
Have added a new option "lockOverflowDrag" in 1.1.0 witch prevents the sheet to be dragget below the first snapPosition and above the last snapPosition. Using `lockOverflowDrag = true` should fix this issue for now until the Flutter team fixes the UiKitView issue.

Have commented on the [Issue](https://github.com/flutter/flutter/issues/24207).

**Comment by salehahmedZ** [comment]
Just tried it. its really good solution. Thank you.
