### ISSUE TITLE
Horizontal snapping

### ISSUE THREAD

**Issue by bdlukaa** [AdamJonsson/snapping_sheet#11]
Is there a way of adding a snapping sheet horizontaly?

**Comment by AdamJonsson** [comment]
Currently, unfortunately not. But great idea for a new feature!

**Comment by C4s4r** [comment]
I love snapping_sheet and was curious if this is still on the plan.
It would help a lot within my new project!

**Comment by AdamJonsson** [comment]
@C4s4r Yes, after the refactoring this seems to not be that hard to implement. I am currently experimenting with adding an `axis` parameter to the snapping sheet widget. I will comment here again when there is an update to this feature :)
