### ISSUE TITLE
Add function to close sheetBelow programmatically

### ISSUE THREAD

**Issue by digarahayu** [AdamJonsson/snapping_sheet#12]
is there any way to close sheet below programmatically, because in my case I use RefreshIndicator when on refresh in sheet below will be show loading widget only that and I updated state  SnapPosition position factor

**Comment by AdamJonsson** [comment]
Hmm, maybe the controller function **snapToPosition** could work for you. I have an example here (Look at onPressed in the FloatingActionButton widget): 
https://github.com/AdamJonsson/snapping_sheet/blob/master/example/lib/listview_example.dart

**Comment by digarahayu** [comment]
oke thanks, the example function onPress FloatingActionButton that what I need
