### ISSUE TITLE
Any plans for null-safety?

### ISSUE THREAD

**Issue by ngxingyu** [AdamJonsson/snapping_sheet#18]

**Comment by Ludonope** [comment]
Hi @AdamJonsson,

Can you migrate the package to null-safety for Flutter 2?

You can follow this guide: https://dart.dev/null-safety/migration-guide

Thanks a lot

**Comment by arsamme** [comment]
@AdamJonsson I can help you migrating package if you accept any PR

**Comment by ngxingyu** [comment]
Working on this.

**Comment by AdamJonsson** [comment]
Thanks to @ngxingyu there exist now a pre-release of null-safety! 🎉
