### ISSUE TITLE
Hide grabbing completely and open it only with the controller

### ISSUE THREAD

**Issue by dvird** [AdamJonsson/snapping_sheet#3]
hi maybe can u add
to hide grabbing completely and open it only with the controller?
and when you open it, you'll see the grabbing only for closing

**Comment by AdamJonsson** [comment]
Thanks for posting a further proposal! I really like the idea of being able to hide and show grabbing from the controller. But I am not entirely sure what you mean by “see the grabbing only for closing” @dvird .

**Comment by dvird** [comment]
Hi thanks :)

"But I am not entirely sure what you mean by “see the grabbing only for closing”
When it closes so you won't be able to see the grabbingview but after you will open the bottomsheet the grabbingview will be still exists for closing it.

i think that all you need to basically is to subtract the height of the grabbing view from initial position subtract

**Comment by dvird** [comment]
a
