### ISSUE TITLE
Error when dragging sheet down

### ISSUE THREAD

**Issue by N1ght-Fury** [AdamJonsson/snapping_sheet#4]
So i dont know how to explain this, but will do my best.
When the app launches and i drag the sheet down while keep holding it, i get the following error:

```
The following NoSuchMethodError was thrown while dispatching a pointer event:
The method '_getPositionInPixels' was called on null.
Receiver: null
Tried calling: _getPositionInPixels(210.0)

When the exception was thrown, this was the stack
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
#1      _SnappingSheetState._getSnapPositionInPixels 
package:snapping_sheet/snapping_sheet.dart:268
#2      _SnappingSheetState._snapToPosition 
package:snapping_sheet/snapping_sheet.dart:250
#3      _SnappingSheetState._animateToClosestStop 
package:snapping_sheet/snapping_sheet.dart:237
#4      _SnappingSheetState._wrapDraggable.<anonymous closure> 
package:snapping_sheet/snapping_sheet.dart:313
...
Event: PointerUpEvent#2f3ce(position: Offset(226.0, 483.0), timeStamp: 60:51:45.292000, pointer: 117, kind: touch, down: false, pressure: 0.2, pressureMin: 0.0)
    position: Offset(226.0, 483.0)
Target: RenderPointerListener#aa8f9
    parentData: right=0.0; bottom=-39.0; left=0.0; height=50.0; offset=Offset(0.0, 249.0) (can use size)
    constraints: BoxConstraints(w=360.0, h=50.0)
    size: Size(360.0, 50.0)
    behavior: translucent
    listeners: down, move, up

```
This happens when you drag it down for the first time after app launches, and without releasing it.
Like i mean i grab it, drag to down of the screen without releasing your finger, and i get this error.
After that snapPositions got broken as well. It stops anywhere on the screen.
If i drag it down than release my finger it works, the problem occurs when i keep going down of the screen without releasing the grabber. And it gets broken.

Here is my code if needed:

```
            SnappingSheet(
                  sheetBelow: Padding(
                    padding: EdgeInsets.only(top: 20.0),
                    child: Align(
                      alignment: Alignment(0.90, -1.0),
                    ),
                  ),
                  onSnapEnd: () {
                    if (_controller.currentSnapPosition.positionFactor == 1.2) {
                      _toggleShowDetailStatus();
                    }
                  },
                  snappingSheetController: _controller,
                  snapPositions: const [
                    SnapPosition(
                        positionFactor: 0.2,
                        snappingCurve: Curves.elasticOut,
                        snappingDuration: Duration(milliseconds: 750)),
                    SnapPosition(positionFactor: 0.6),
                    SnapPosition(positionFactor: 1.0),
                    SnapPosition(positionFactor: 1.2),
                  ],
                  initSnapPosition: SnapPosition(positionFactor: 0.6),
                  grabbingHeight: MediaQuery.of(context).padding.bottom + 50,
                  grabbing: GrabSection(),
                  sheetAbove: _sheetContent(),
                )

```

This is my first submitting an issue on github so im sorry if the format is wrong or something. I can provide any additional informations if needed.

I also added a video of the problem which will makes things more clearer i guess. The same problem also occurs on your Example app you created.

Screen record link: https://streamable.com/mmllg

edit1: added code block
edit2: I want to fix that the error doesnt only occur after app launches but whenever i reopen the snap sheet. Hope the video will make it clear.

**Comment by AdamJonsson** [comment]
Thank you for creating the issue, helped me a lot with your detailed description. I have uploaded a new version that fixes the issue, let me know if it works. 😄 
Fix in 83fcf24bbbb0e2940e728869828735765f8aae97

**Comment by N1ght-Fury** [comment]
Thank you so much for your work! I just tested it and it works perfctly fine right now. Thank you again!

By the way, i have found one more issue. Idk if i should call it a bug or not (its not related to this one). Should i open a new issue for that?

**Comment by AdamJonsson** [comment]
Nice! Yea, if you have the time I would appreciate it 😄
