### ISSUE TITLE
sheetBelow parameter should not be marked as @required

### ISSUE THREAD

**Issue by Nico04** [AdamJonsson/snapping_sheet#5]
When using your [topsheet example](https://github.com/AdamJonsson/snapping_sheet/blob/master/example/lib/topsheet_example.dart), if I do not need the FloatingActionButton, Android Studio remind you that sheetBelow parameters is required, which doesn't makes sense in that case.
It's not very important, just not relevant.

**Comment by AdamJonsson** [comment]
You are right, thank you 😄
Fixed in 5212e76f9f9ef674aeddf8e01ec2f8fdda4d8fe4
