### ISSUE TITLE
Allow multiple Snapping Sheets

### ISSUE THREAD

**Issue by kamami** [AdamJonsson/snapping_sheet#52]
Is there any way to add trigger different Snapping Sheets with different configurations (e.g snappingPositions, grabbingHeight, etc.)? Currently each Snapping Sheet needs to have one child. But I would like to have multiple sheets for this single child.

**Comment by AdamJonsson** [comment]
Hmm, not sure if I fully understand, but do you mean that you want multiple children in one of the sheetAbove and sheetBelow parameters? One simple solution would be to pass a column widget into the child parameter.

```dart

    sheetAbove: SnappingSheetContent(
        draggable: true,
        child: Column(
          children: [
            Text("First child"),
            Text("Second child"),
            Text("Third child"),
          ],
        ),
    ),

```

Is this what you are after, or is it something else?

**Comment by kamami** [comment]
No, that is not what I am looking for.
I would like to see two completely different SnappingSheets based on a value (eg. index = 0).

`                 SnappingSheet(
                              controller: _snappingController,
                              lockOverflowDrag: true,
                              child: Container(),
                              sheetBelow: index = 0 ? 
                                                      SnappingSheetContent(
                                                         draggable: true,
                                                         child: Container(color: red))
                                                   : SnappingSheetContent(
                                                         draggable: true,
                                                         child: Container(color: blue))
`
![image](https://user-images.githubusercontent.com/43880037/114997434-1e957780-9ea0-11eb-951c-8899a65b831e.png)

I want to show two different SnappingSheets based on the selected index of the bottom navigation bar. (I do not use tabview or pageview, because I want to always show the same map)

Any suggestions how to solve this?

**Comment by AdamJonsson** [comment]
Okay, so you want to have two different SnappingSheet widgets that share the same child? That is, you want to change the snapping sheet without changing the child widget, which in your case is the GoogleMaps widget. Is that correct?

**Comment by kamami** [comment]
Yes, I guess we are on the same page now. 
Do you have any suggestions to realize this?
Best would be to also have two different controllers for both snapping sheets!

**Comment by AdamJonsson** [comment]
Personally, I would create a Stack with the snapping sheets and pass in SizedBox in the child parameter.  
```dart
        Stack(
          children: [
            GoogleMapsWidget(),
            toggle
                ? SnappingSheet(
                    child: SizedBox(),
                    key: UniqueKey(),
                    grabbing: ...,
                  )
                : SnappingSheet(
                    child: SizedBox(),
                    key: UniqueKey(),
                    grabbing: ...,
                  )
          ],
        ),
```
However, I should make it the child optional to make it more clear that a child is not necessary .

**Comment by kamami** [comment]
Thanks for the suggestion, I think this could work!
The only problem I still have, is that the controller of the second snapping sheet is not attached to the widget when I switch the to the second tab...
Any idea how to solve this problem?

This is the erros message, when switching to the second tab:
`SnappingSheet must be attached before calling any function from the controller. Pass in the
controller to the snapping sheet widget to attached. Use [isAttached] to check if it is attached or
not.
`
