### ISSUE TITLE
Fix gesturedetection for buttons inside grabbing widget

### ISSUE THREAD

**Issue by AdamJonsson** [AdamJonsson/snapping_sheet#6]
Issue from: *"...The SnappingCheat reacts to a "single tap" in the grabber section. Therefore I'm looking for way that the grabber won't listen to taps, because I have buttons in this section and the SnappingSheet should not move when the user just taps these buttons."*

**Comment by AdamJonsson** [comment]
This should be resolved in the latest update of the package. This is because the sheet no longer moves to another snap position when the grabbing widget is tapped.

**Comment by M4iK26** [comment]
Works flawlessly now, thanks for the fix! SnappingSheet is a big part of my app and therefore very important.
