### ISSUE TITLE
GrabbingWidget wrong position at bottom

### ISSUE THREAD

**Issue by valentingrigorean** [AdamJonsson/snapping_sheet#62]
GrabbingWidget get cut in half when you set 
```dart
initialSnappingPosition:
          const SnappingPosition.factor(positionFactor: 0.4),
snappingPositions: const [
  const SnappingPosition.factor(
    positionFactor: 0.8,
    grabbingContentOffset: GrabbingContentOffset.middle,
  ),
  const SnappingPosition.factor(
    positionFactor: 0.4,
    grabbingContentOffset: GrabbingContentOffset.top,
  ),
  const SnappingPosition.factor(
    positionFactor: 0.0,
    grabbingContentOffset: GrabbingContentOffset.middle,
  ),
],
```

When the SnappingPosition is 0.0 will do
https://github.com/AdamJonsson/snapping_sheet/blob/f46832b8b7c428fb618c5c76fa7e54e04d8fdf63/lib/src/snapping_sheet_widget.dart#L311

A fix will be to change to 
```dart
final position = max(_currentPosition - widget.grabbingHeight / 2, 0.0);
```

It's working for the below sheet didn't test if this will work for the top sheet.

**Comment by AdamJonsson** [comment]
If you want the grabbing widget to be fully visible at the 0.0 position, you should set the `grabbingContentOffset` to `GrabbingContentOffset.top`. So you last snapping position in the example shoudl be:

```dart
SnappingPosition.factor(
  positionFactor: 0.0,
  grabbingContentOffset: GrabbingContentOffset.top,
),
```

Is that solving your problem or have I misinterpreted your issue?

**Comment by valentingrigorean** [comment]
yea your right I didn't read the documentation for grabbingContentOffset. Thanks for the help.
