### ISSUE TITLE
Snapping positions not working as expected with controller

### ISSUE THREAD

**Issue by mikechari** [AdamJonsson/snapping_sheet#67]
Hi, I have 2 snapping points as follows:

```
snappingPositions: [
    SnappingPosition.pixels(
    positionPixels: context.percentWidth * 0, 
    snappingCurve: Curves.decelerate,
    snappingDuration: const Duration(milliseconds: 400),
    grabbingContentOffset: GrabbingContentOffset.top,
),
    SnappingPosition.pixels(
    positionPixels: context.percentWidth * 40,
    snappingCurve: Curves.decelerate,
   snappingDuration: const Duration(milliseconds: 400),
),], 
```

When I drag the snapping sheet the snapping positions works as expected but when I try to hide de sheet using a control and the same snapping position the sheet hides a bit like this:

`                        draggableController.snapToPosition(
                            SnappingPosition.pixels(positionPixels: 0));`

Is this intended?, is there a way to make the controller to move exactly to the same as the snappingPositions?

thanks

**Comment by AdamJonsson** [comment]
I think that you could use the `grabbingContentOffset,` parameter when specifying the snapping position in the controller. For example: 

```dart
draggableController.snapToPosition( 
    SnappingPosition.pixels(
        positionPixels: 0,
        grabbingContentOffset: GrabbingContentOffset.top,
    )
);
```

**Comment by mikechari** [comment]
That did the trick, thank you!
