### ISSUE TITLE
rotation problems

### ISSUE THREAD

**Issue by MahdiPishguy** [AdamJonsson/snapping_sheet#8]
### problem one

![Screenshot_20200325-110528](https://user-images.githubusercontent.com/6617583/77508682-e1bba480-6e88-11ea-86dd-e4bb27fe4956.jpg)
![Screenshot_20200325-110533](https://user-images.githubusercontent.com/6617583/77508691-e4b69500-6e88-11ea-9fe2-8c7afdbc8199.jpg)

### problem two:

![Screenshot_20200325-110554](https://user-images.githubusercontent.com/6617583/77508700-eb450c80-6e88-11ea-9929-e9ef44e4e0a8.jpg)
![Screenshot_20200325-110601](https://user-images.githubusercontent.com/6617583/77508704-ee3ffd00-6e88-11ea-9e95-5af5d495792d.jpg)

**Comment by AdamJonsson** [comment]
This is now fixed in 2.0.1! Thank you for finding this issue 😄
