### ISSUE TITLE
grabbing transparency 

### ISSUE THREAD

**Issue by gpigatto** [AdamJonsson/snapping_sheet#9]
There's any way to set transparency in the grabber?

**Comment by AdamJonsson** [comment]
You can give the grabber an opacity widget:
```dart
grabbing: Opacity(
    opacity: 0.5,
    child: Container(
        color: Colors.red
    ),
),
```

**Comment by gpigatto** [comment]
> You can give the grabber an opacity widget:
> 
> ```dart
> grabbing: Opacity(
>     opacity: 0.5,
>     child: Container(
>         color: Colors.red
>     ),
> ),
> ```

this, don't do the trick

**Comment by gpigatto** [comment]
I was using the sheetAbove as child, this lead me to this problem

**Comment by AdamJonsson** [comment]
@gpigatto Do you think you can describe the problem that you are getting and the code that causing the problem?

**Comment by gpigatto** [comment]
I was using: 

`return SnappingSheet(
      grabbing: _grabbing(),
      sheetAbove: _home(),
      sheetBelow: _bottomSheet(),
    );
  }
`

Causing this: 
![image](https://user-images.githubusercontent.com/12770899/78914138-63522b80-7a60-11ea-97e3-9eb79c56b774.png)

Instead of : 

`return SnappingSheet(
      grabbing: _grabbing(),
      child: _home(),
      sheetBelow: _bottomSheet(),
    );
  }
`
This was the objective: 
![image](https://user-images.githubusercontent.com/12770899/78914212-7c5adc80-7a60-11ea-8da1-ef53fc67816c.png)

**Comment by AdamJonsson** [comment]
Ahh, okay I see. So everything is working now?

**Comment by gpigatto** [comment]
yes, it was my fault, i should have paid more attention

**Comment by AdamJonsson** [comment]
No worries, I can be easy to miss what all the parameters are doing 😃
